name: Donna Testing

on:
  push:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test-on-ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install pytest-xvfb
        pip install .
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Test with pytest
      run: |
        pytest-xvfb --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=donna tests/ | tee pytest-coverage.txt
    - name: Coverage report generation
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
