name: Donna

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-on-ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

    - name: Setup virtual display
      run: |
        sudo apt-get update && sudo apt-get install -y software-properties-common unzip curl xvfb

    - name: Test with xvfb-run pytest
      run: |
        xvfb-run python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=donna tests/ | tee pytest-coverage.txt

    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@v1.1.28
      with:
        default-branch: master
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml

    - name: Create variable of summary report
      id: summary_report
      run: |
        SUMMARY_REPORT=${{ steps.coverageComment.outputs.summaryReport }}
        echo "::set-output name=content::$SUMMARY_REPORT"

    - name: Update Readme with coverage Html
      id: readmeUpdate
      if: github.event_name == 'push'
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\n\${{ steps.coverageComment.outputs.coverageHtml }}\n\n\${{ steps.summary_report.outputs.content }}\n\n<!-- Pytest Coverage Comment:End -->' ./README.md

    - name: Create PR for changes to Readme
      id: cpr
      if: steps.readmeUpdate.outcome == 'success'
      uses: peter-evans/create-pull-request@v4.0.4
      with:
        branch: workflow-readme-update
        base: master
        title: "[skip ci] README Update"
        labels: automerge
        commit-message: Update coverage on Readme
        token: ${{ secrets.PAT_TOKEN }}

    - name: Auto approve Readme change PR
      id: approvePR
      if: steps.cpr.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.cpr.outputs.pull-request-number }}

    - name: Enable automerge for Readme update PR
      if: steps.approvePR.outcome == 'success'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash
